/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author yasmi
 */
public class BD_Gestao_GUI extends javax.swing.JFrame {

    static int id_professor;
    static String nome_professor;
    static int id_chave;
    static String nome_chave;
    static int id_item;
    static String nome_item;
    
    String url = "jdbc:mysql://localhost/sle";
    String username = "root";
    String password = "";
    
    public BD_Gestao_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProfTXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ItensTXT = new javax.swing.JTextField();
        AddItem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ChavesTXT = new javax.swing.JTextField();
        AddChave = new javax.swing.JButton();
        BotaoVoltar = new javax.swing.JButton();
        AddProf = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        RemChave = new javax.swing.JButton();
        ChavesCBJ = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        ItensCBJ = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        RemItem = new javax.swing.JButton();
        ProfCBJ = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        RemProf = new javax.swing.JButton();
        BotaoVoltar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SLE (C) - CEAP");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 212, 515, 20);
        jPanel1.add(ProfTXT);
        ProfTXT.setBounds(10, 29, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Adicionar Itens");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 65, 170, 14);
        jPanel1.add(ItensTXT);
        ItensTXT.setBounds(10, 83, 170, 30);

        AddItem.setText("ADD");
        AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemActionPerformed(evt);
            }
        });
        jPanel1.add(AddItem);
        AddItem.setBounds(186, 83, 60, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Adicionar Chaves");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 119, 170, 14);
        jPanel1.add(ChavesTXT);
        ChavesTXT.setBounds(10, 137, 170, 30);

        AddChave.setText("ADD");
        AddChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddChaveActionPerformed(evt);
            }
        });
        jPanel1.add(AddChave);
        AddChave.setBounds(186, 137, 60, 30);

        BotaoVoltar.setText("Voltar");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(BotaoVoltar);
        BotaoVoltar.setBounds(441, 170, 80, 30);

        AddProf.setText("ADD");
        AddProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProfActionPerformed(evt);
            }
        });
        jPanel1.add(AddProf);
        AddProf.setBounds(186, 29, 60, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Adicionar Professores");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 11, 170, 14);

        RemChave.setText("Remover");
        jPanel1.add(RemChave);
        RemChave.setBounds(265, 140, 90, 20);

        jPanel1.add(ChavesCBJ);
        ChavesCBJ.setBounds(360, 140, 160, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Remover Chaves");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(360, 120, 160, 20);

        jPanel1.add(ItensCBJ);
        ItensCBJ.setBounds(360, 90, 160, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Remover Itens");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(360, 70, 160, 20);

        RemItem.setText("Remover");
        jPanel1.add(RemItem);
        RemItem.setBounds(265, 90, 90, 20);

        jPanel1.add(ProfCBJ);
        ProfCBJ.setBounds(360, 40, 160, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Remover Professores");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 20, 160, 20);

        RemProf.setText("Remover");
        jPanel1.add(RemProf);
        RemProf.setBounds(265, 40, 90, 20);

        BotaoVoltar1.setText("Voltar");
        BotaoVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltar1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotaoVoltar1);
        BotaoVoltar1.setBounds(460, 170, 61, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(539, 232));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        
        new Home_GUI().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void BotaoVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoVoltar1ActionPerformed

    private void AddProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProfActionPerformed
        
        nome_professor = ProfTXT.getText();
        
        controller.Conexao_DB.carregaDriver();

        Connection con = null;
        
        try{
            con = (Connection) DriverManager.getConnection(url, username, password);
        } catch (SQLException ex) {
            Logger.getLogger(BD_Gestao_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String SQL = "insert into professores(nome_prof) values('"+nome_professor+"')";
        
        try{
            PreparedStatement insert = (PreparedStatement) con.prepareStatement(SQL);
            insert.execute();
            
            ProfTXT.setText("");
            
        }catch (Exception ex) {
            Logger.getLogger(BD_Gestao_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_AddProfActionPerformed

    private void AddChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddChaveActionPerformed
        
        nome_chave = ChavesTXT.getText();
        
        controller.Conexao_DB.carregaDriver();

        Connection con = null;
        
        try{
            con = (Connection) DriverManager.getConnection(url, username, password);
        } catch (SQLException ex) {
            Logger.getLogger(BD_Gestao_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String SQL = "insert into chaves(nome_chave) values('"+nome_chave+"')";
        
        try{
            PreparedStatement insert = (PreparedStatement) con.prepareStatement(SQL);
            insert.execute();
            
            ChavesTXT.setText("");
            
        }catch (Exception ex) {
            Logger.getLogger(BD_Gestao_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_AddChaveActionPerformed

    private void AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemActionPerformed
       
        nome_item = ItensTXT.getText();
        
        controller.Conexao_DB.carregaDriver();

        Connection con = null;
        
        try{
            con = (Connection) DriverManager.getConnection(url, username, password);
        } catch (SQLException ex) {
            Logger.getLogger(BD_Gestao_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String SQL = "insert into itens(nome_item) values('"+nome_item+"')";
        
        try{
            PreparedStatement insert = (PreparedStatement) con.prepareStatement(SQL);
            insert.execute();
            
            ItensTXT.setText("");
            
        }catch (Exception ex) {
            Logger.getLogger(BD_Gestao_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_AddItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BD_Gestao_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BD_Gestao_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BD_Gestao_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BD_Gestao_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BD_Gestao_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddChave;
    private javax.swing.JButton AddItem;
    private javax.swing.JButton AddProf;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JButton BotaoVoltar1;
    private javax.swing.JComboBox ChavesCBJ;
    private javax.swing.JTextField ChavesTXT;
    private javax.swing.JComboBox ItensCBJ;
    private javax.swing.JTextField ItensTXT;
    private javax.swing.JComboBox ProfCBJ;
    private javax.swing.JTextField ProfTXT;
    private javax.swing.JButton RemChave;
    private javax.swing.JButton RemItem;
    private javax.swing.JButton RemProf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
